import createScreenLayoutContract from '../../foundation/layout/createScreenLayoutContract'
import { spacing } from '../../foundation/tokens'

const layoutContract = createScreenLayoutContract({
  screenId: 'projects',
  screenName: 'ProjectsScreen',
  includeDefaultBodySplit: false,
  bodyBackdrop: { preset: 'default' },
  layer2: [
    {
      name: 'Layer2_Projects_Backdrop',
      layer: 'Layer2',
      parent: 'Layer1_Body_ScreenBodyField',
      semanticRole: 'body-backdrop',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        gridColumn: '1',
        gridRow: '1',
        minWidth: 0,
        minHeight: 0,
        position: 'relative',
        pointerEvents: 'none',
      },
    },
    {
      name: 'Layer2_Projects_Root',
      layer: 'Layer2',
      parent: 'Layer1_Body_ScreenBodyField',
      semanticRole: 'content-owner',
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateColumns: 'minmax(0, 1fr)',
      gridTemplateRows: 'auto auto',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: `${spacing[32]} ${spacing[32]} ${spacing[48]}`,
      gap: spacing[32],
      overflow: 'auto',
      textAlign: 'left',
      style: {
        gridColumn: '1',
        gridRow: '1',
        minWidth: 0,
        minHeight: 0,
        width: '100%',
        maxWidth: '1240px',
        marginInline: 'auto',
        position: 'relative',
        zIndex: 1,
      },
      mobile: {
        padding: `${spacing[24]} ${spacing[16]} ${spacing[40]}`,
        gap: spacing[24],
        // Content-size the rows and pack them from the top. Without this the
        // stretched full-height root split its `auto auto` rows into two equal
        // tracks, so the hero overflowed its half onto the summary band (R-020).
        alignContent: 'start',
      },
    },
  ],
  layer3: [
    {
      name: 'Layer3_Projects_Orientation',
      layer: 'Layer3',
      parent: 'Layer2_Projects_Root',
      semanticRole: 'orientation-zone',
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateColumns: 'minmax(0, 1fr)',
      gridTemplateRows: 'auto auto',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: spacing[32],
      overflow: 'visible',
      textAlign: 'left',
      style: { gridRow: '1', minWidth: 0 },
      mobile: { gap: spacing[24], alignContent: 'start' },
    },
    {
      name: 'Layer3_Projects_Workspace',
      layer: 'Layer3',
      parent: 'Layer2_Projects_Root',
      semanticRole: 'primary-work-pane',
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateColumns: '380px minmax(0, 1fr) 58px',
      alignItems: 'start',
      justifyContent: 'stretch',
      padding: '0',
      gap: spacing[40],
      overflow: 'visible',
      textAlign: 'left',
      style: { gridRow: '2', minWidth: 0, minHeight: 0 },
      mobile: {
        // Flex column, not a single-column grid: a stretched full-height grid
        // split its implicit rows into equal tracks, so the lesson rail and the
        // detail stage overlapped. Flex stacks them at content height (R-020).
        display: 'flex',
        flexDirection: 'column',
        gap: spacing[24],
      },
    },
  ],
  layer4: [
    {
      name: 'Layer4_Projects_Hero',
      layer: 'Layer4',
      parent: 'Layer3_Projects_Orientation',
      semanticRole: 'header-zone',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'left',
      style: { gridRow: '1', minWidth: 0 },
    },
    {
      name: 'Layer4_Projects_Summary',
      layer: 'Layer4',
      parent: 'Layer3_Projects_Orientation',
      semanticRole: 'summary-band',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'left',
      style: { gridRow: '2', minWidth: 0 },
    },
    {
      name: 'Layer4_Projects_LessonRail',
      layer: 'Layer4',
      parent: 'Layer3_Projects_Workspace',
      semanticRole: 'navigation-pane',
      allowEmpty: true,
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'left',
      style: { gridColumn: '1', minWidth: 0, minHeight: 0 },
      // flexShrink 0 in the mobile flex column: the rail must keep its content
      // height, not collapse and let its list overflow onto the detail stage.
      mobile: { gridColumn: '1', flexShrink: 0 },
    },
    {
      name: 'Layer4_Projects_DetailStage',
      layer: 'Layer4',
      parent: 'Layer3_Projects_Workspace',
      semanticRole: 'primary-action-region',
      allowEmpty: true,
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'left',
      style: { gridColumn: '2', minWidth: 0, minHeight: 0 },
      mobile: { gridColumn: '1', flexShrink: 0 },
    },
    {
      name: 'Layer4_Projects_History',
      layer: 'Layer4',
      parent: 'Layer3_Projects_Workspace',
      semanticRole: 'support-rail',
      allowEmpty: true,
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'center',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'left',
      style: { gridColumn: '3', minWidth: 0, minHeight: 0, alignSelf: 'stretch' },
      mobile: { display: 'none' },
    },
  ],
})

export default layoutContract
