import createScreenLayoutContract from './createScreenLayoutContract'
import { spacing } from '../tokens'

export default function createLabBoardContract({ screenId, screenName }) {
  return createScreenLayoutContract({
    screenId,
    screenName,
    bodyBackdrop: { preset: 'default' },
    layer3: [
      {
        name: 'Layer3_Lab_LeftNav',
        layer: 'Layer3',
        parent: 'Layer2_Body_ContentStartRail',
        display: 'flex',
        layoutMode: 'flex',
        flexDirection: 'column',
        alignItems: 'stretch',
        justifyContent: 'flex-start',
        padding: '0',
        gap: spacing[12],
        overflow: 'visible',
        textAlign: 'left',
      },
      {
        name: 'Layer3_Lab_CenterStack',
        layer: 'Layer3',
        parent: 'Layer2_Body_ContentCenterField',
        display: 'flex',
        layoutMode: 'flex',
        flexDirection: 'column',
        alignItems: 'stretch',
        justifyContent: 'flex-start',
        padding: `${spacing[16]} 0`,
        gap: spacing[16],
        overflow: 'auto',
        textAlign: 'left',
        style: {
          minHeight: '100%',
        },
      },
      {
        name: 'Layer3_Lab_Hero',
        layer: 'Layer3',
        parent: 'Layer3_Lab_CenterStack',
        display: 'flex',
        layoutMode: 'flex',
        flexDirection: 'column',
        alignItems: 'stretch',
        justifyContent: 'flex-start',
        padding: spacing[28],
        gap: spacing[16],
        overflow: 'hidden',
        textAlign: 'left',
      },
      {
        name: 'Layer3_Lab_Content',
        layer: 'Layer3',
        parent: 'Layer3_Lab_CenterStack',
        display: 'flex',
        layoutMode: 'flex',
        flexDirection: 'column',
        alignItems: 'stretch',
        justifyContent: 'flex-start',
        padding: '0',
        gap: spacing[16],
        overflow: 'visible',
        textAlign: 'left',
      },
      {
        name: 'Layer3_Lab_RightRail',
        layer: 'Layer3',
        parent: 'Layer2_Body_ContentEndRail',
        display: 'flex',
        layoutMode: 'flex',
        flexDirection: 'column',
        alignItems: 'stretch',
        justifyContent: 'flex-start',
        padding: '0',
        gap: spacing[12],
        overflow: 'visible',
        textAlign: 'left',
      },
    ],
  })
}
