import { colors, spacing } from '../tokens'
import { controlSizing } from '../tokens/controlSizing'
import { getDefaultBodySplitColumns, getLayer1BodyColumns, shellSizing } from './shellSizing'

export const rootContainerName = 'Layer1_Stage_ScreenShell'

export function getUniversalShellContainers() {
  return [
    {
      name: rootContainerName,
      layer: 'Layer1',
      parent: null,
      semanticRole: 'stage',
      as: 'main',
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateRows: `${shellSizing.header.heightPx} minmax(0, 1fr)`,
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        minHeight: '100vh',
        background: [
          'radial-gradient(circle at 8% 10%, rgba(219, 234, 254, 0.78), transparent 28%)',
          'radial-gradient(circle at 88% 12%, rgba(226, 232, 240, 0.82), transparent 24%)',
          `linear-gradient(180deg, ${colors.bgTop} 0%, ${colors.bgBottom} 100%)`,
        ].join(', '),
        color: colors.textStrong,
      },
    },
    {
      name: 'Layer1_Header_Row',
      layer: 'Layer1',
      parent: rootContainerName,
      semanticRole: 'shell-header-band',
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateColumns: '6fr 18fr 6fr',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        borderBottom: `1px solid ${colors.lineSoft}`,
        background: 'rgba(255, 255, 255, 0.92)',
        backdropFilter: 'blur(18px)',
      },
    },
    {
      name: 'Layer1_Header_StartLane',
      layer: 'Layer1',
      parent: 'Layer1_Header_Row',
      semanticRole: 'shell-safe-inset-lane',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-start',
      padding: `0 clamp(${spacing[16]}, 2.2vw, ${spacing[32]})`,
      gap: spacing[16],
      overflow: 'visible',
      textAlign: 'left',
    },
    {
      name: 'Layer1_Header_CenterLane',
      layer: 'Layer1',
      parent: 'Layer1_Header_Row',
      semanticRole: 'shell-safe-inset-lane',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: `0 clamp(${spacing[12]}, 1.6vw, ${spacing[16]})`,
      gap: spacing[16],
      overflow: 'visible',
      textAlign: 'center',
    },
    {
      name: 'Layer1_Header_EndLane',
      layer: 'Layer1',
      parent: 'Layer1_Header_Row',
      semanticRole: 'shell-safe-inset-lane',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-end',
      padding: `0 clamp(${spacing[16]}, 2.2vw, ${spacing[32]})`,
      gap: spacing[16],
      overflow: 'visible',
      textAlign: 'right',
    },
    {
      name: 'Layer1_Body_Row',
      layer: 'Layer1',
      parent: rootContainerName,
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateColumns: getLayer1BodyColumns(),
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
    },
    {
      name: 'Layer1_Body_NavigationRail',
      layer: 'Layer1',
      parent: 'Layer1_Body_Row',
      semanticRole: 'shell-chrome',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      // Horizontal padding is derived from the control it holds, not chosen
      // alongside it, so the content lane always fits a rail control exactly.
      padding: `${spacing[20]} max(0px, calc((100% - ${controlSizing.navRailControlPx}px) / 2))`,
      gap: spacing[16],
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        borderRight: `1px solid ${colors.lineSoft}`,
        background: 'rgba(255, 255, 255, 0.84)',
        backdropFilter: 'blur(18px)',
      },
    },
    {
      name: 'Layer1_Navigation_HeaderBand',
      layer: 'Layer1',
      parent: 'Layer1_Body_NavigationRail',
      semanticRole: 'shell-chrome',
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateColumns: 'minmax(0, 1fr) auto',
      alignItems: 'start',
      justifyContent: 'stretch',
      padding: '0',
      gap: spacing[12],
      overflow: 'visible',
      textAlign: 'left',
      style: {
        minHeight: '32px',
      },
    },
    {
      name: 'Layer1_Navigation_BrandAnchor',
      layer: 'Layer1',
      parent: 'Layer1_Navigation_HeaderBand',
      semanticRole: 'shell-chrome',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-start',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'left',
    },
    {
      name: 'Layer1_Navigation_UtilityAnchor',
      layer: 'Layer1',
      parent: 'Layer1_Navigation_HeaderBand',
      semanticRole: 'shell-chrome',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'center',
      justifyContent: 'flex-end',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'right',
      style: {
        minWidth: '28px',
      },
    },
    {
      name: 'Layer1_Navigation_PrimaryList',
      layer: 'Layer1',
      parent: 'Layer1_Body_NavigationRail',
      semanticRole: 'shell-chrome',
      as: 'nav',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: '0',
      gap: spacing[12],
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        flex: 1,
      },
    },
    {
      name: 'Layer1_Body_ScreenBodyField',
      layer: 'Layer1',
      parent: 'Layer1_Body_Row',
      semanticRole: 'screen-body-field',
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateColumns: 'minmax(0, 1fr)',
      gridTemplateRows: 'minmax(0, 1fr)',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        minWidth: 0,
        minHeight: 0,
      },
    },
  ]
}

export function getDefaultBodySplitContainers() {
  return [
    {
      name: 'Layer2_Body_Backdrop',
      layer: 'Layer2',
      parent: 'Layer1_Body_ScreenBodyField',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        gridColumn: '1',
        gridRow: '1',
        minWidth: 0,
        minHeight: 0,
        position: 'relative',
        pointerEvents: 'none',
        background: [
          'radial-gradient(circle at 18% 16%, rgba(219, 234, 254, 0.7), transparent 24%)',
          'radial-gradient(circle at 84% 14%, rgba(226, 232, 240, 0.72), transparent 22%)',
          `linear-gradient(180deg, ${colors.surfaceSoft} 0%, rgba(255, 255, 255, 0.78) 100%)`,
        ].join(', '),
      },
    },
    {
      name: 'Layer2_Body_DefaultSplit',
      layer: 'Layer2',
      parent: 'Layer1_Body_ScreenBodyField',
      semanticRole: 'body-split',
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateColumns: getDefaultBodySplitColumns(),
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        gridColumn: '1',
        gridRow: '1',
        minHeight: 0,
        position: 'relative',
        zIndex: 1,
      },
    },
    {
      name: 'Layer2_Body_ContentStartRail',
      layer: 'Layer2',
      parent: 'Layer2_Body_DefaultSplit',
      semanticRole: 'support-rail',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: `${spacing[24]} ${spacing[20]}`,
      gap: spacing[20],
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        gridColumn: '1',
        gridRow: '1',
      },
    },
    {
      name: 'Layer2_Body_ContentCenterField',
      layer: 'Layer2',
      parent: 'Layer2_Body_DefaultSplit',
      semanticRole: 'content-owner',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: `${spacing[24]} ${spacing[24]} ${spacing[32]}`,
      gap: spacing[24],
      overflow: 'auto',
      textAlign: 'left',
      style: {
        gridColumn: '2',
        gridRow: '1',
        minWidth: 0,
        minHeight: 0,
        width: '100%',
      },
    },
    {
      name: 'Layer2_Body_ContentEndRail',
      layer: 'Layer2',
      parent: 'Layer2_Body_DefaultSplit',
      semanticRole: 'support-rail',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: `${spacing[24]} ${spacing[20]}`,
      gap: spacing[20],
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        gridColumn: '3',
        gridRow: '1',
      },
    },
  ]
}
