import createScreenLayoutContract from '../../foundation/layout/createScreenLayoutContract'
import { spacing } from '../../foundation/tokens'

const layoutContract = createScreenLayoutContract({
  screenId: 'studyWorkspace',
  screenName: 'StudyWorkspaceScreen',
  includeDefaultBodySplit: false,
  bodyBackdrop: { preset: 'default' },
  layer2: [
    {
      name: 'Layer2_Body_Backdrop',
      layer: 'Layer2',
      parent: 'Layer1_Body_ScreenBodyField',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        gridColumn: '1',
        gridRow: '1',
        minWidth: 0,
        minHeight: 0,
        position: 'relative',
        pointerEvents: 'none',
      },
    },
    {
      name: 'Layer2_Study_WorkspaceRoot',
      layer: 'Layer2',
      parent: 'Layer1_Body_ScreenBodyField',
      semanticRole: 'study-workspace-root',
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateColumns: 'minmax(196px, 224px) minmax(0, 1fr) minmax(320px, 376px)',
      gridTemplateRows: 'minmax(0, 1fr)',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        gridColumn: '1',
        gridRow: '1',
        minWidth: 0,
        minHeight: 0,
        position: 'relative',
        zIndex: 1,
      },
    },
  ],
  layer3: [
    {
      name: 'Layer3_Study_SegmentNavigator',
      layer: 'Layer3',
      parent: 'Layer2_Study_WorkspaceRoot',
      semanticRole: 'segment-navigation-rail',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        minWidth: 0,
        minHeight: 0,
      },
    },
    {
      name: 'Layer3_Study_CenterWorkspace',
      layer: 'Layer3',
      parent: 'Layer2_Study_WorkspaceRoot',
      semanticRole: 'primary-work-pane',
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateRows: 'auto minmax(0, 1fr) auto',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        minWidth: 0,
        minHeight: 0,
      },
    },
    {
      name: 'Layer3_Study_SupportRail',
      layer: 'Layer3',
      parent: 'Layer2_Study_WorkspaceRoot',
      semanticRole: 'support-rail',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        minWidth: 0,
        minHeight: 0,
      },
    },
  ],
  layer4: [
    {
      name: 'Layer4_Study_CenterHeader',
      layer: 'Layer4',
      parent: 'Layer3_Study_CenterWorkspace',
      semanticRole: 'header-zone',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'left',
      style: {
        minWidth: 0,
        flex: '0 0 auto',
      },
    },
    {
      name: 'Layer4_Study_PrimaryScroll',
      layer: 'Layer4',
      parent: 'Layer3_Study_CenterWorkspace',
      semanticRole: 'primary-scroll-owner',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: '0',
      gap: spacing[16],
      overflow: 'auto',
      textAlign: 'left',
      style: {
        minWidth: 0,
        minHeight: 0,
      },
    },
    {
      name: 'Layer4_Study_ActionRegion',
      layer: 'Layer4',
      parent: 'Layer3_Study_CenterWorkspace',
      semanticRole: 'action-region',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-end',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'left',
      style: {
        minWidth: 0,
        flex: '0 0 auto',
      },
    },
  ],
})

export default layoutContract
