import createScreenLayoutContract from '../../foundation/layout/createScreenLayoutContract'
import { colors, elevation, radius, spacing } from '../../foundation/tokens'

export const layoutContract = createScreenLayoutContract({
  screenId: 'foundationLab',
  screenName: 'FoundationLabScreen',
  bodyBackdrop: { preset: 'default' },
  layer3: [
    {
      name: 'Layer3_Lab_LeftSummary',
      layer: 'Layer3',
      parent: 'Layer2_Body_ContentStartRail',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: '0',
      gap: spacing[12],
      overflow: 'visible',
      textAlign: 'left',
    },
    {
      name: 'Layer3_Lab_CenterStack',
      layer: 'Layer3',
      parent: 'Layer2_Body_ContentCenterField',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: `${spacing[16]} 0`,
      gap: spacing[16],
      overflow: 'auto',
      textAlign: 'left',
      style: {
        minHeight: '100%',
      },
    },
    {
      name: 'Layer3_Lab_HeroPanel',
      layer: 'Layer3',
      parent: 'Layer3_Lab_CenterStack',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: spacing[28],
      gap: spacing[16],
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        border: `1px solid ${colors.lineSoft}`,
        borderRadius: radius[32],
        background: 'rgba(255, 255, 255, 0.96)',
        boxShadow: elevation.rest,
      },
    },
    {
      name: 'Layer3_Lab_CategoryGrid',
      layer: 'Layer3',
      parent: 'Layer3_Lab_CenterStack',
      display: 'grid',
      layoutMode: 'grid',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: spacing[12],
      overflow: 'visible',
      textAlign: 'left',
      style: {
        gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
      },
    },
    {
      name: 'Layer3_Lab_PreviewPanel',
      layer: 'Layer3',
      parent: 'Layer3_Lab_CenterStack',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: spacing[24],
      gap: spacing[16],
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        border: `1px solid ${colors.lineSoft}`,
        borderRadius: radius[24],
        background: 'rgba(255, 255, 255, 0.96)',
        boxShadow: elevation.flat,
      },
    },
    {
      name: 'Layer3_Lab_RightChecklist',
      layer: 'Layer3',
      parent: 'Layer2_Body_ContentEndRail',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: '0',
      gap: spacing[12],
      overflow: 'visible',
      textAlign: 'left',
    },
  ],
})

export default layoutContract
