import type { AuditFinding } from '../../policy/findingSchema.ts'

export interface RuntimeQaGateDefinition {
  gateLabel: string
  ruleId: string
  title: string
  category: string
  subcategory: string | null
  severity: AuditFinding['severity']
  confidence: AuditFinding['confidence']
  classification: AuditFinding['classification']
  ownerLayer: AuditFinding['ownerLayer']
  suggestedFix: string
  suggestedActionType: string
}

export const runtimeQaGateDefinitions: Record<string, RuntimeQaGateDefinition> = {
  'wrapper depth': {
    gateLabel: 'wrapper depth',
    ruleId: 'wrapper-depth',
    title: 'Excessive wrapper depth',
    category: 'runtime-integrity',
    subcategory: 'structure',
    severity: 'warn',
    confidence: 'high',
    classification: 'real-code-fix',
    ownerLayer: 'runtime-qa',
    suggestedFix: 'Flatten unnecessary wrapper layers so the rendered structure stays legible and maintainable.',
    suggestedActionType: 'code-change',
  },
  'overlap check': {
    gateLabel: 'overlap check',
    ruleId: 'overlap',
    title: 'Rendered overlap',
    category: 'runtime-integrity',
    subcategory: 'layout',
    severity: 'error',
    confidence: 'high',
    classification: 'real-code-fix',
    ownerLayer: 'runtime-qa',
    suggestedFix: 'Fix the owning layout so text and controls no longer collide at the failing viewport or stress state.',
    suggestedActionType: 'code-change',
  },
  'layer ancestry': {
    gateLabel: 'layer ancestry',
    ruleId: 'layer-ancestry',
    title: 'Layer ancestry drift',
    category: 'runtime-integrity',
    subcategory: 'structure',
    severity: 'warn',
    confidence: 'high',
    classification: 'real-code-fix',
    ownerLayer: 'runtime-qa',
    suggestedFix: 'Restore the intended layer ownership so later-layer containers sit inside the correct ancestors.',
    suggestedActionType: 'code-change',
  },
  'empty containers': {
    gateLabel: 'empty containers',
    ruleId: 'empty-container',
    title: 'Empty runtime container',
    category: 'runtime-integrity',
    subcategory: 'container-hygiene',
    severity: 'warn',
    confidence: 'high',
    classification: 'real-code-fix',
    ownerLayer: 'runtime-qa',
    suggestedFix: 'Remove the empty container or give it an explicit structural role if it is intentionally empty.',
    suggestedActionType: 'code-change',
  },
  'pass-through containers': {
    gateLabel: 'pass-through containers',
    ruleId: 'pass-through-container',
    title: 'Pass-through runtime container',
    category: 'runtime-integrity',
    subcategory: 'container-hygiene',
    severity: 'warn',
    confidence: 'high',
    classification: 'real-code-fix',
    ownerLayer: 'runtime-qa',
    suggestedFix: 'Remove or justify the pass-through container so the runtime structure stays honest.',
    suggestedActionType: 'code-change',
  },
  'child containment': {
    gateLabel: 'child containment',
    ruleId: 'child-containment',
    title: 'Child containment failure',
    category: 'runtime-integrity',
    subcategory: 'layout',
    severity: 'error',
    confidence: 'high',
    classification: 'real-code-fix',
    ownerLayer: 'runtime-qa',
    suggestedFix: 'Fix the parent layout or containment model so children stay inside their owners.',
    suggestedActionType: 'code-change',
  },
  'fixed structural sizing': {
    gateLabel: 'fixed structural sizing',
    ruleId: 'fixed-structural-sizing',
    title: 'Fixed structural sizing drift',
    category: 'runtime-integrity',
    subcategory: 'sizing',
    severity: 'warn',
    confidence: 'high',
    classification: 'real-code-fix',
    ownerLayer: 'runtime-qa',
    suggestedFix: 'Replace the unapproved fixed structural size with a tokenized or contract-owned sizing pattern.',
    suggestedActionType: 'code-change',
  },
  'readable inset': {
    gateLabel: 'readable inset',
    ruleId: 'readable-inset',
    title: 'Readable inset failure',
    category: 'runtime-integrity',
    subcategory: 'spacing',
    severity: 'warn',
    confidence: 'high',
    classification: 'real-code-fix',
    ownerLayer: 'runtime-qa',
    suggestedFix: 'Increase the owning inset or rebalance the layout so meaningful content does not crowd the edge.',
    suggestedActionType: 'code-change',
  },
  'padding discipline': {
    gateLabel: 'padding discipline',
    ruleId: 'spacing-scale-discipline',
    title: 'Spacing scale drift',
    category: 'runtime-integrity',
    subcategory: 'spacing',
    severity: 'warn',
    confidence: 'high',
    classification: 'real-code-fix',
    ownerLayer: 'runtime-qa',
    suggestedFix: 'Bring the rendered spacing values back onto the approved spacing scale.',
    suggestedActionType: 'code-change',
  },
  'primary width': {
    gateLabel: 'primary width',
    ruleId: 'primary-width',
    title: 'Primary width drift',
    category: 'runtime-integrity',
    subcategory: 'composition',
    severity: 'warn',
    confidence: 'high',
    classification: 'real-code-fix',
    ownerLayer: 'runtime-qa',
    suggestedFix: 'Adjust the shell or composition so the primary work region stays within the approved width range.',
    suggestedActionType: 'code-change',
  },
  'orphan overrides': {
    gateLabel: 'orphan overrides',
    ruleId: 'orphan-override-key',
    title: 'Orphan override key',
    category: 'runtime-integrity',
    subcategory: 'contract',
    severity: 'error',
    confidence: 'high',
    classification: 'real-code-fix',
    ownerLayer: 'runtime-qa',
    suggestedFix: 'Remove the orphan override or point it at a declared contract container.',
    suggestedActionType: 'code-change',
  },
  'contract/container mismatch': {
    gateLabel: 'contract/container mismatch',
    ruleId: 'contract-render-mismatch',
    title: 'Contract/render mismatch',
    category: 'runtime-integrity',
    subcategory: 'contract',
    severity: 'error',
    confidence: 'high',
    classification: 'real-code-fix',
    ownerLayer: 'runtime-qa',
    suggestedFix: 'Bring the rendered debug container tree back into agreement with the declared contract.',
    suggestedActionType: 'code-change',
  },
  'debug coverage': {
    gateLabel: 'debug coverage',
    ruleId: 'debug-coverage-missing',
    title: 'Missing debug coverage',
    category: 'runtime-integrity',
    subcategory: 'debug',
    severity: 'warn',
    confidence: 'high',
    classification: 'real-code-fix',
    ownerLayer: 'runtime-qa',
    suggestedFix: 'Name the missing meaningful UI items in debug so QA can inspect them directly.',
    suggestedActionType: 'code-change',
  },
  'full-height composition': {
    gateLabel: 'full-height composition',
    ruleId: 'composition-integrity',
    title: 'Composition integrity failure',
    category: 'runtime-integrity',
    subcategory: 'composition',
    severity: 'error',
    confidence: 'high',
    classification: 'real-code-fix',
    ownerLayer: 'runtime-qa',
    suggestedFix: 'Restore the full-height composition so the center stack fills correctly and action/workspace stay attached.',
    suggestedActionType: 'code-change',
  },
  'ordered gutter yield': {
    gateLabel: 'ordered gutter yield',
    ruleId: 'ordered-gutter-yield',
    title: 'Ordered gutter yield failure',
    category: 'runtime-integrity',
    subcategory: 'viewport-stress',
    severity: 'warn',
    confidence: 'high',
    classification: 'real-code-fix',
    ownerLayer: 'runtime-qa',
    suggestedFix: 'Adjust shell width negotiation so gutters yield before the center drifts under viewport stress.',
    suggestedActionType: 'code-change',
  },
}

export function getRuntimeQaGateDefinition(gateLabel: string) {
  return runtimeQaGateDefinitions[gateLabel] ?? {
    gateLabel,
    ruleId: gateLabel.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, ''),
    title: gateLabel,
    category: 'runtime-integrity',
    subcategory: 'unknown',
    severity: 'warn',
    confidence: 'medium',
    classification: 'low-confidence-review',
    ownerLayer: 'runtime-qa',
    suggestedFix: 'Review this runtime gate failure and decide whether it needs a code fix or a QA rule adjustment.',
    suggestedActionType: 'review',
  } satisfies RuntimeQaGateDefinition
}
