import type { StaticDoctrineRuleDefinition } from './types.ts'

export const staticDoctrineRuleDefinitions: Record<string, StaticDoctrineRuleDefinition> = {
  'hardcoded-typography': {
    ruleId: 'hardcoded-typography',
    title: 'Hardcoded typography literal',
    category: 'doctrine',
    subcategory: 'typography',
    severity: 'warn',
    confidence: 'medium',
    suggestedFix: 'Replace the literal with a typography token or an explicit named variant.',
    suggestedActionType: 'code-change',
  },
  'hardcoded-spacing': {
    ruleId: 'hardcoded-spacing',
    title: 'Hardcoded spacing literal',
    category: 'doctrine',
    subcategory: 'spacing',
    severity: 'warn',
    confidence: 'medium',
    suggestedFix: 'Replace the literal with spacing tokens or an approved surface padding role.',
    suggestedActionType: 'code-change',
  },
  'hardcoded-color': {
    ruleId: 'hardcoded-color',
    title: 'Hardcoded color literal',
    category: 'doctrine',
    subcategory: 'color',
    severity: 'info',
    confidence: 'medium',
    suggestedFix: 'Replace the literal with a shared color token or an approved color role.',
    suggestedActionType: 'code-change',
  },
  'hardcoded-radius': {
    ruleId: 'hardcoded-radius',
    title: 'Hardcoded radius literal',
    category: 'doctrine',
    subcategory: 'radius',
    severity: 'info',
    confidence: 'medium',
    suggestedFix: 'Replace the literal with a shared radius token or an allowed inherited radius pattern.',
    suggestedActionType: 'code-change',
  },
  'hardcoded-motion': {
    ruleId: 'hardcoded-motion',
    title: 'Hardcoded motion literal',
    category: 'doctrine',
    subcategory: 'motion',
    severity: 'info',
    confidence: 'medium',
    suggestedFix: 'Replace the literal with a named motion token or role.',
    suggestedActionType: 'code-change',
  },
  'container-overrides-usage': {
    ruleId: 'container-overrides-usage',
    title: 'Screen-level container override drift',
    category: 'generic-ownership',
    subcategory: 'container-overrides',
    severity: 'info',
    confidence: 'medium',
    suggestedFix: 'Confirm the override is truly screen-specific and not compensating for a weak generic.',
    suggestedActionType: 'review',
  },
  'shell-override-touchpoint': {
    ruleId: 'shell-override-touchpoint',
    title: 'Screen-level shell override touchpoint',
    category: 'shell-discipline',
    subcategory: 'shared-shell',
    severity: 'warn',
    confidence: 'high',
    suggestedFix: 'Move shell ownership back into the shared shell layer unless this is an explicit doctrine exception.',
    suggestedActionType: 'code-change',
  },
  'screen-local-shell-math-bypass': {
    ruleId: 'screen-local-shell-math-bypass',
    title: 'Screen-local shell sizing bypass',
    category: 'shell-discipline',
    subcategory: 'shell-math',
    severity: 'warn',
    confidence: 'high',
    suggestedFix: 'Use approved shared shell sizing ownership instead of local shell width/ratio math.',
    suggestedActionType: 'code-change',
  },
  'screen-local-bespoke-variant': {
    ruleId: 'screen-local-bespoke-variant',
    title: 'Screen-local bespoke variant',
    category: 'generic-ownership',
    subcategory: 'screen-local-variant',
    severity: 'warn',
    confidence: 'medium',
    suggestedFix: 'Promote this into a named token or shared variant if it is intentional.',
    suggestedActionType: 'review',
  },
  'contract-duplicate-container': {
    ruleId: 'contract-duplicate-container',
    title: 'Duplicate contract container',
    category: 'contract',
    subcategory: 'duplicate-container',
    severity: 'error',
    confidence: 'high',
    suggestedFix: 'Remove or rename the duplicate contract container entry.',
    suggestedActionType: 'code-change',
  },
  'contract-missing-parent': {
    ruleId: 'contract-missing-parent',
    title: 'Missing contract parent',
    category: 'contract',
    subcategory: 'missing-parent',
    severity: 'error',
    confidence: 'high',
    suggestedFix: 'Point the contract node to an existing parent container.',
    suggestedActionType: 'code-change',
  },
  'contract-allow-empty-without-role': {
    ruleId: 'contract-allow-empty-without-role',
    title: 'allowEmpty without semantic role',
    category: 'contract',
    subcategory: 'allow-empty',
    severity: 'error',
    confidence: 'high',
    suggestedFix: 'Add a semanticRole to the allowEmpty container.',
    suggestedActionType: 'code-change',
  },
  'override-key-missing-container': {
    ruleId: 'override-key-missing-container',
    title: 'Override key without matching container',
    category: 'contract',
    subcategory: 'override-key',
    severity: 'error',
    confidence: 'high',
    suggestedFix: 'Point the override at a declared contract container or a valid shared shell container.',
    suggestedActionType: 'code-change',
  },
}
