export const duplicationPolicy = {
  ignoredFileKinds: ['token-definition', 'generated', 'ignored', 'unknown'] as const,
  styleBundle: {
    minPropertyCount: 5,
    minSurfacePropertyCount: 2,
    minUniqueFiles: 2,
    signatureProperties: [
      'background',
      'backgroundColor',
      'border',
      'borderColor',
      'borderRadius',
      'borderTopLeftRadius',
      'borderTopRightRadius',
      'borderBottomLeftRadius',
      'borderBottomRightRadius',
      'boxShadow',
      'padding',
      'paddingInline',
      'paddingBlock',
      'paddingTop',
      'paddingRight',
      'paddingBottom',
      'paddingLeft',
      'gap',
      'rowGap',
      'columnGap',
      'minHeight',
      'height',
      'minWidth',
      'width',
      'color',
      'outline',
      'outlineColor',
      'fill',
      'stroke',
    ],
    surfaceProperties: ['background', 'backgroundColor', 'border', 'borderColor', 'borderRadius', 'boxShadow', 'padding'],
    contextNamePattern: /(style|surface|card|panel|pill|chip|button|banner|tone|chrome)/i,
  },
  shellMath: {
    minUniqueFiles: 2,
    propertyNames: ['width', 'minWidth', 'maxWidth', 'height', 'minHeight', 'maxHeight', 'gridTemplateColumns', 'gridTemplateRows', 'gridTemplate', 'flexBasis'],
    namePattern: /(shell|split|track|gutter|column|columns|row|rows|width|rail|pane|body|field|band)/i,
    strongPattern: /(clamp\(|calc\(|minmax\()/i,
    interestingMinmaxPattern: /minmax\((?:max-content|[^,]+\$\{expr\}|[^,]+fr)/i,
    ignoredExactFormulas: ['repeat(2, minmax(0, 1fr))', 'repeat(4, minmax(0, 1fr))'],
  },
  contractFragment: {
    minFieldCount: 8,
    minUniqueFiles: 3,
    selectedFields: [
      'display',
      'layoutMode',
      'flexDirection',
      'alignItems',
      'justifyContent',
      'padding',
      'gap',
      'overflow',
      'textAlign',
      'semanticRole',
      'allowEmpty',
      'gridTemplateColumns',
      'gridTemplateRows',
    ],
  },
  variantDrift: {
    minPropertyCount: 5,
    minDistinctSignatures: 2,
    minUniqueFiles: 2,
    eligibleFileKinds: ['shared-layout', 'shared-primitive', 'framework-adapter'] as const,
  },
} as const
