import createScreenLayoutContract from '../../foundation/layout/createScreenLayoutContract'
import { colors, elevation, radius, spacing } from '../../foundation/tokens'

export const layoutContract = createScreenLayoutContract({
  screenId: 'appLaunch',
  screenName: 'AppLaunchScreen',
  bodyBackdrop: { preset: 'default' },
  layer3: [
    {
      name: 'Layer3_Launch_LeftSupport',
      layer: 'Layer3',
      parent: 'Layer2_Body_ContentStartRail',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-end',
      padding: '0',
      gap: spacing[16],
      overflow: 'visible',
      textAlign: 'left',
    },
    {
      name: 'Layer3_Launch_CenterBand',
      layer: 'Layer3',
      parent: 'Layer2_Body_ContentCenterField',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'center',
      padding: `${spacing[32]}px 0`,
      gap: spacing[24],
      overflow: 'visible',
      textAlign: 'left',
      style: {
        minHeight: '100%',
      },
    },
    {
      name: 'Layer3_Launch_HeroPanel',
      layer: 'Layer3',
      parent: 'Layer3_Launch_CenterBand',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'center',
      padding: spacing[48],
      gap: spacing[24],
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        border: `1px solid ${colors.lineSoft}`,
        borderRadius: radius[32],
        background: 'rgba(255, 255, 255, 0.96)',
        boxShadow: elevation.rest,
      },
    },
    {
      name: 'Layer3_Launch_ActionBand',
      layer: 'Layer3',
      parent: 'Layer3_Launch_HeroPanel',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      padding: '0',
      gap: spacing[12],
      overflow: 'visible',
      textAlign: 'left',
      style: {
        flexWrap: 'wrap',
      },
    },
    {
      name: 'Layer3_Launch_RightSupport',
      layer: 'Layer3',
      parent: 'Layer2_Body_ContentEndRail',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: '0',
      gap: spacing[16],
      overflow: 'visible',
      textAlign: 'left',
    },
  ],
})

export default layoutContract
