import createScreenLayoutContract from '../../foundation/layout/createScreenLayoutContract'
import { radius, spacing } from '../../foundation/tokens'

const panelSurfaceStyle = {
  border: `1px solid rgba(15, 23, 42, 0.08)`,
  borderRadius: radius[32],
  background: 'rgba(255, 255, 255, 0.98)',
  boxShadow: '0 2px 20px -4px rgba(0, 0, 0, 0.06)',
}

export const layoutContract = createScreenLayoutContract({
  screenId: 'segmentationPaste',
  screenName: 'SegmentationPasteScreen',
  bodyBackdrop: { preset: 'default' },
  layer3: [
    {
      name: 'Layer3_Segmentation_CenterBands',
      layer: 'Layer3',
      parent: 'Layer2_Body_ContentCenterField',
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateRows: '1fr 2fr 1fr 10fr 3fr',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        minHeight: '100%',
      },
    },
  ],
  layer4: [
    {
      name: 'Layer4_Segmentation_ModeBand',
      layer: 'Layer4',
      parent: 'Layer3_Segmentation_CenterBands',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '0',
      gap: spacing[8],
      overflow: 'visible',
      textAlign: 'center',
    },
    {
      name: 'Layer4_Segmentation_HeaderBand',
      layer: 'Layer4',
      parent: 'Layer3_Segmentation_CenterBands',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '0',
      gap: spacing[8],
      overflow: 'hidden',
      textAlign: 'center',
      style: {
        minWidth: 0,
      },
    },
    {
      name: 'Layer4_Segmentation_ContextBand',
      layer: 'Layer4',
      parent: 'Layer3_Segmentation_CenterBands',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '0',
      gap: spacing[12],
      overflow: 'hidden',
      textAlign: 'center',
      style: {
        minWidth: 0,
      },
    },
    {
      name: 'Layer4_Segmentation_WorkspaceBand',
      layer: 'Layer4',
      parent: 'Layer3_Segmentation_CenterBands',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'stretch',
      justifyContent: 'center',
      padding: `10px ${spacing[20]}px 12px`,
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        minHeight: 0,
      },
    },
    {
      name: 'Layer4_Segmentation_ActionBand',
      layer: 'Layer4',
      parent: 'Layer3_Segmentation_CenterBands',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: `6px ${spacing[20]}px 18px`,
      gap: '0',
      overflow: 'visible',
      textAlign: 'center',
      style: {
        minHeight: 0,
      },
    },
    {
      name: 'Layer5_Segmentation_WorkspaceFrame',
      layer: 'Layer5',
      parent: 'Layer4_Segmentation_WorkspaceBand',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'left',
      style: {
        position: 'relative',
        width: '100%',
        minHeight: 0,
        padding: '12px 10px 16px',
      },
    },
    {
      name: 'Layer5_Segmentation_SourcePanel',
      layer: 'Layer5',
      parent: 'Layer5_Segmentation_WorkspaceFrame',
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateRows: 'auto minmax(0, 1fr) auto',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        ...panelSurfaceStyle,
        width: '100%',
        minHeight: 0,
        position: 'relative',
      },
    },
    {
      name: 'Layer5_Segmentation_SourcePanelTopbar',
      layer: 'Layer5',
      parent: 'Layer5_Segmentation_SourcePanel',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: `${spacing[16]}px ${spacing[20]}px`,
      gap: spacing[12],
      overflow: 'visible',
      textAlign: 'left',
      style: {
        minHeight: '60px',
        borderBottom: `1px solid rgba(0, 0, 0, 0.05)`,
        background: '#ffffff',
        flexWrap: 'wrap',
      },
    },
    {
      name: 'Layer5_Segmentation_SourcePanelBody',
      layer: 'Layer5',
      parent: 'Layer5_Segmentation_SourcePanel',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        minHeight: 0,
        position: 'relative',
      },
    },
    {
      name: 'Layer5_Segmentation_SourcePanelFooter',
      layer: 'Layer5',
      parent: 'Layer5_Segmentation_SourcePanel',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: `0 ${spacing[20]}px`,
      gap: spacing[12],
      overflow: 'visible',
      textAlign: 'left',
      style: {
        minHeight: '38px',
        borderTop: `1px solid rgba(0, 0, 0, 0.05)`,
        flexWrap: 'wrap',
      },
    },
    {
      name: 'Layer5_Segmentation_ActionDock',
      layer: 'Layer5',
      parent: 'Layer4_Segmentation_ActionBand',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'center',
      style: {
        width: '100%',
        height: '100%',
        position: 'relative',
      },
    },
  ],
})

export default layoutContract
