import createScreenLayoutContract from '../../foundation/layout/createScreenLayoutContract'
import { spacing } from '../../foundation/tokens'

const layoutContract = createScreenLayoutContract({
  screenId: 'projectResearch',
  screenName: 'ProjectResearchScreen',
  includeDefaultBodySplit: false,
  bodyBackdrop: { preset: 'default' },
  layer2: [
    {
      name: 'Layer2_Body_Backdrop',
      layer: 'Layer2',
      parent: 'Layer1_Body_ScreenBodyField',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        gridColumn: '1',
        gridRow: '1',
        minWidth: 0,
        minHeight: 0,
        position: 'relative',
        pointerEvents: 'none',
      },
    },
    {
      name: 'Layer2_ProjectResearch_Root',
      layer: 'Layer2',
      parent: 'Layer1_Body_ScreenBodyField',
      semanticRole: 'project-research-workspace-root',
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateRows: 'auto minmax(0, 1fr)',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: `clamp(${spacing[16]}, 2vw, ${spacing[24]})`,
      gap: spacing[16],
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        gridColumn: '1',
        gridRow: '1',
        minWidth: 0,
        minHeight: 0,
        position: 'relative',
        zIndex: 1,
      },
    },
  ],
  layer3: [
    {
      name: 'Layer3_ProjectResearch_Header',
      layer: 'Layer3',
      parent: 'Layer2_ProjectResearch_Root',
      semanticRole: 'project-research-header',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'left',
      style: {
        minWidth: 0,
      },
    },
    {
      name: 'Layer3_ProjectResearch_Main',
      layer: 'Layer3',
      parent: 'Layer2_ProjectResearch_Root',
      semanticRole: 'project-research-main-workspace',
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateColumns: 'minmax(188px, 216px) minmax(0, 1fr)',
      gridTemplateRows: 'minmax(0, 1fr)',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: spacing[16],
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        minWidth: 0,
        minHeight: 0,
      },
    },
  ],
  layer4: [
    {
      name: 'Layer4_ProjectResearch_FilterRail',
      layer: 'Layer4',
      parent: 'Layer3_ProjectResearch_Main',
      semanticRole: 'project-knowledge-filter-rail',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        minWidth: 0,
        minHeight: 0,
      },
    },
    {
      name: 'Layer4_ProjectResearch_ResultSurface',
      layer: 'Layer4',
      parent: 'Layer3_ProjectResearch_Main',
      semanticRole: 'project-knowledge-result-surface',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'flex-start',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        minWidth: 0,
        minHeight: 0,
      },
    },
  ],
})

export default layoutContract
