import createScreenLayoutContract from '../../foundation/layout/createScreenLayoutContract'
import { getDefaultBodySplitColumns } from '../../foundation/layout/shellSizing'
import { spacing } from '../../foundation/tokens'

function frTemplate(values) {
  return values.map((value) => `${value}fr`).join(' ')
}

function adaptiveFrRows(values) {
  return values.map((value) => `minmax(max-content, ${value}fr)`).join(' ')
}

const layoutContract = createScreenLayoutContract({
  screenId: 'segmentationPasteNext',
  screenName: 'SegmentationPasteNextScreen',
  includeDefaultBodySplit: false,
  bodyBackdrop: { preset: 'default' },
  layer2: [
    {
      name: 'Layer2_Body_Backdrop',
      layer: 'Layer2',
      parent: 'Layer1_Body_ScreenBodyField',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        gridColumn: '1',
        gridRow: '1',
        minWidth: 0,
        minHeight: 0,
        position: 'relative',
        pointerEvents: 'none',
      },
    },
    {
      name: 'Layer2_Body_DefaultSplit',
      layer: 'Layer2',
      parent: 'Layer1_Body_ScreenBodyField',
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateColumns: getDefaultBodySplitColumns(),
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        gridColumn: '1',
        gridRow: '1',
        minWidth: 0,
        minHeight: 0,
        position: 'relative',
        zIndex: 1,
      },
    },
    {
      name: 'Layer2_Body_ContentCenterField',
      layer: 'Layer2',
      parent: 'Layer2_Body_DefaultSplit',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: `${spacing[24]} ${spacing[24]} ${spacing[32]}`,
      gap: '0',
      overflow: 'auto',
      textAlign: 'left',
      style: {
        gridColumn: '2',
        gridRow: '1',
        minWidth: 0,
        minHeight: 0,
        width: '100%',
      },
    },
  ],
  layer3: [
    {
      name: 'Layer3_SegmentationNext_OperationalStack',
      layer: 'Layer3',
      parent: 'Layer2_Body_ContentCenterField',
      semanticRole: 'composition-owner',
      display: 'grid',
      layoutMode: 'grid',
      gridTemplateRows: adaptiveFrRows([0.4, 0.25, 0.1, 0.5, 0.1, 0.25, 0.4, 5, 2]),
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'hidden',
      textAlign: 'left',
      style: {
        minWidth: 0,
        minHeight: 0,
        flex: 1,
      },
    },
  ],
  layer4: [
    {
      name: 'Layer4_SegmentationNext_TopBreathingBand',
      layer: 'Layer4',
      parent: 'Layer3_SegmentationNext_OperationalStack',
      allowEmpty: true,
      semanticRole: 'breathing-band',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'left',
      style: {
        gridRow: '1',
        minHeight: 0,
        minWidth: 0,
      },
    },
    {
      name: 'Layer4_SegmentationNext_ModeBand',
      layer: 'Layer4',
      parent: 'Layer3_SegmentationNext_OperationalStack',
      semanticRole: 'full-span-band',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '0',
      gap: spacing[8],
      overflow: 'visible',
      textAlign: 'center',
      style: {
        gridRow: '2',
        minWidth: 0,
        minHeight: 0,
      },
    },
    {
      name: 'Layer4_SegmentationNext_ModeHeaderBreathingBand',
      layer: 'Layer4',
      parent: 'Layer3_SegmentationNext_OperationalStack',
      allowEmpty: true,
      semanticRole: 'breathing-band',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'left',
      style: {
        gridRow: '3',
        minHeight: 0,
        minWidth: 0,
      },
    },
    {
      name: 'Layer4_SegmentationNext_HeaderBand',
      layer: 'Layer4',
      parent: 'Layer3_SegmentationNext_OperationalStack',
      semanticRole: 'full-span-band',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '0',
      gap: spacing[8],
      overflow: 'visible',
      textAlign: 'center',
      style: {
        gridRow: '4',
        minWidth: 0,
        minHeight: 0,
      },
    },
    {
      name: 'Layer4_SegmentationNext_HeaderContextBreathingBand',
      layer: 'Layer4',
      parent: 'Layer3_SegmentationNext_OperationalStack',
      allowEmpty: true,
      semanticRole: 'breathing-band',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'left',
      style: {
        gridRow: '5',
        minHeight: 0,
        minWidth: 0,
      },
    },
    {
      name: 'Layer4_SegmentationNext_ContextBand',
      layer: 'Layer4',
      parent: 'Layer3_SegmentationNext_OperationalStack',
      semanticRole: 'full-span-band',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: '0',
      gap: spacing[12],
      overflow: 'visible',
      textAlign: 'center',
      style: {
        gridRow: '6',
        minWidth: 0,
        minHeight: 0,
      },
    },
    {
      name: 'Layer4_SegmentationNext_ContextWorkspaceBreathingBand',
      layer: 'Layer4',
      parent: 'Layer3_SegmentationNext_OperationalStack',
      allowEmpty: true,
      semanticRole: 'breathing-band',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'left',
      style: {
        gridRow: '7',
        minHeight: 0,
        minWidth: 0,
      },
    },
    {
      name: 'Layer4_SegmentationNext_WorkspaceBand',
      layer: 'Layer4',
      parent: 'Layer3_SegmentationNext_OperationalStack',
      semanticRole: 'full-span-band',
      display: 'flex',
      layoutMode: 'flex',
      alignItems: 'stretch',
      justifyContent: 'stretch',
      padding: '0',
      gap: '0',
      overflow: 'visible',
      textAlign: 'left',
      style: {
        gridRow: '8',
        minHeight: 0,
        minWidth: 0,
      },
    },
    {
      name: 'Layer4_SegmentationNext_ActionBand',
      layer: 'Layer4',
      parent: 'Layer3_SegmentationNext_OperationalStack',
      semanticRole: 'full-span-band',
      display: 'flex',
      layoutMode: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      padding: `${spacing[12]} ${spacing[20]} ${spacing[24]}`,
      gap: spacing[12],
      overflow: 'visible',
      textAlign: 'center',
      style: {
        gridRow: '9',
        minHeight: 0,
        minWidth: 0,
        position: 'relative',
        zIndex: 3,
      },
    },
  ],
})

export default layoutContract
